USE fantasy_f1;

-- Svuota tutte le tabelle mantenendo invariata la struttura del database.
-- TRUNCATE azzera anche i contatori AUTO_INCREMENT.
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE RISULTATO_TEAM;
TRUNCATE TABLE PARTECIPAZIONE_TEAM;
TRUNCATE TABLE PRESTAZIONE_WEEKEND;
TRUNCATE TABLE COMPOSIZIONE_TEAM;
TRUNCATE TABLE PILOTA_ISCRITTO;
TRUNCATE TABLE LEGA;
TRUNCATE TABLE TEAM_FANTASY;
TRUNCATE TABLE SCUDERIA_ISCRITTA;
TRUNCATE TABLE WEEKEND_DI_GARA;
TRUNCATE TABLE UTENTE;
TRUNCATE TABLE SCUDERIA;
TRUNCATE TABLE PILOTA;
TRUNCATE TABLE GRAN_PREMIO;
TRUNCATE TABLE EDIZIONE;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
