DROP DATABASE IF EXISTS fantasy_f1;

CREATE DATABASE fantasy_f1
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE fantasy_f1;

CREATE TABLE EDIZIONE (
    IdEdizione INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NumeroEdizione INT UNSIGNED NOT NULL,
    Anno YEAR NOT NULL,
    CONSTRAINT PK_EDIZIONE PRIMARY KEY (IdEdizione),
    CONSTRAINT UQ_EDIZIONE_NUMERO UNIQUE (NumeroEdizione),
    CONSTRAINT UQ_EDIZIONE_ANNO UNIQUE (Anno)
);

CREATE TABLE GRAN_PREMIO (
    IdGranPremio INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Circuito VARCHAR(100) NOT NULL,
    Nazione VARCHAR(80) NOT NULL,
    Città VARCHAR(80) NOT NULL,
    CONSTRAINT PK_GRAN_PREMIO PRIMARY KEY (IdGranPremio),
    CONSTRAINT UQ_GRAN_PREMIO_NOME UNIQUE (Nome)
);

CREATE TABLE PILOTA (
    IdPilota INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    Nazionalità VARCHAR(50) NOT NULL,
    DataNascita DATE NOT NULL,
    CONSTRAINT PK_PILOTA PRIMARY KEY (IdPilota)
);

CREATE TABLE SCUDERIA (
    IdScuderia INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SCUDERIA PRIMARY KEY (IdScuderia),
    CONSTRAINT UQ_SCUDERIA_NOME UNIQUE (Nome)
);

CREATE TABLE UTENTE (
    IdUtente INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    Username VARCHAR(50) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(254) NOT NULL,
    Telefono VARCHAR(20) NOT NULL,
    CONSTRAINT PK_UTENTE PRIMARY KEY (IdUtente),
    CONSTRAINT UQ_UTENTE_USERNAME UNIQUE (Username),
    CONSTRAINT UQ_UTENTE_EMAIL UNIQUE (Email)
);

CREATE TABLE WEEKEND_DI_GARA (
    IdEdizione INT UNSIGNED NOT NULL,
    IdGranPremio INT UNSIGNED NOT NULL,
    NumeroRound INT UNSIGNED NOT NULL,
    DataInizio DATE NOT NULL,
    DataFine DATE NOT NULL,
    CONSTRAINT PK_WEEKEND_DI_GARA
        PRIMARY KEY (IdEdizione, IdGranPremio),
    CONSTRAINT UQ_WEEKEND_EDIZIONE_ROUND
        UNIQUE (IdEdizione, NumeroRound),
    CONSTRAINT CK_WEEKEND_NUMERO_ROUND
        CHECK (NumeroRound BETWEEN 1 AND 24),
    CONSTRAINT CK_WEEKEND_DATE
        CHECK (DataFine >= DataInizio),
    CONSTRAINT FK_WEEKEND_GRAN_PREMIO
        FOREIGN KEY (IdGranPremio)
        REFERENCES GRAN_PREMIO (IdGranPremio),
    CONSTRAINT FK_WEEKEND_EDIZIONE
        FOREIGN KEY (IdEdizione)
        REFERENCES EDIZIONE (IdEdizione)
);

CREATE TABLE SCUDERIA_ISCRITTA (
    IdEdizione INT UNSIGNED NOT NULL,
    IdScuderia INT UNSIGNED NOT NULL,
    NomeIscrizione VARCHAR(100) NOT NULL,
    NomeVettura VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SCUDERIA_ISCRITTA
        PRIMARY KEY (IdEdizione, IdScuderia),
    CONSTRAINT UQ_SCUDERIA_ISCRITTA_NOME
        UNIQUE (IdEdizione, NomeIscrizione),
    CONSTRAINT FK_SCUDERIA_ISCRITTA_SCUDERIA
        FOREIGN KEY (IdScuderia)
        REFERENCES SCUDERIA (IdScuderia),
    CONSTRAINT FK_SCUDERIA_ISCRITTA_EDIZIONE
        FOREIGN KEY (IdEdizione)
        REFERENCES EDIZIONE (IdEdizione)
);

CREATE TABLE TEAM_FANTASY (
    IdTeam INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    PunteggioTotale INT NOT NULL,
    IdUtente INT UNSIGNED NOT NULL,
    IdEdizione INT UNSIGNED NOT NULL,
    CONSTRAINT PK_TEAM_FANTASY PRIMARY KEY (IdTeam),
    CONSTRAINT UQ_TEAM_FANTASY_NOME
        UNIQUE (Nome, IdUtente, IdEdizione),
    CONSTRAINT UQ_TEAM_FANTASY_ID_EDIZIONE
        UNIQUE (IdTeam, IdEdizione),
    CONSTRAINT FK_TEAM_FANTASY_UTENTE
        FOREIGN KEY (IdUtente)
        REFERENCES UTENTE (IdUtente),
    CONSTRAINT FK_TEAM_FANTASY_EDIZIONE
        FOREIGN KEY (IdEdizione)
        REFERENCES EDIZIONE (IdEdizione)
);

CREATE TABLE LEGA (
    IdLega INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    IdUtente INT UNSIGNED NOT NULL,
    IdEdizione INT UNSIGNED NOT NULL,
    CONSTRAINT PK_LEGA PRIMARY KEY (IdLega),
    CONSTRAINT UQ_LEGA_NOME
        UNIQUE (Nome, IdUtente, IdEdizione),
    CONSTRAINT FK_LEGA_UTENTE
        FOREIGN KEY (IdUtente)
        REFERENCES UTENTE (IdUtente),
    CONSTRAINT FK_LEGA_EDIZIONE
        FOREIGN KEY (IdEdizione)
        REFERENCES EDIZIONE (IdEdizione)
);

CREATE TABLE PILOTA_ISCRITTO (
    IdEdizione INT UNSIGNED NOT NULL,
    IdPilota INT UNSIGNED NOT NULL,
    SiglaGara CHAR(3) NOT NULL,
    NumeroInGara INT UNSIGNED NOT NULL,
    IdScuderia INT UNSIGNED NOT NULL,
    CONSTRAINT PK_PILOTA_ISCRITTO
        PRIMARY KEY (IdEdizione, IdPilota),
    CONSTRAINT UQ_PILOTA_ISCRITTO_SIGLA
        UNIQUE (IdEdizione, SiglaGara),
    CONSTRAINT UQ_PILOTA_ISCRITTO_NUMERO
        UNIQUE (IdEdizione, NumeroInGara),
    CONSTRAINT FK_PILOTA_ISCRITTO_PILOTA
        FOREIGN KEY (IdPilota)
        REFERENCES PILOTA (IdPilota),
    CONSTRAINT FK_PILOTA_ISCRITTO_EDIZIONE
        FOREIGN KEY (IdEdizione)
        REFERENCES EDIZIONE (IdEdizione),
    CONSTRAINT FK_PILOTA_ISCRITTO_SCUDERIA
        FOREIGN KEY (IdEdizione, IdScuderia)
        REFERENCES SCUDERIA_ISCRITTA (IdEdizione, IdScuderia)
);

CREATE TABLE COMPOSIZIONE_TEAM (
    IdEdizione INT UNSIGNED NOT NULL,
    IdPilota INT UNSIGNED NOT NULL,
    IdTeam INT UNSIGNED NOT NULL,
    CONSTRAINT PK_COMPOSIZIONE_TEAM
        PRIMARY KEY (IdTeam, IdEdizione, IdPilota),
    CONSTRAINT FK_COMPOSIZIONE_TEAM_TEAM
        FOREIGN KEY (IdTeam, IdEdizione)
        REFERENCES TEAM_FANTASY (IdTeam, IdEdizione),
    CONSTRAINT FK_COMPOSIZIONE_TEAM_PILOTA
        FOREIGN KEY (IdEdizione, IdPilota)
        REFERENCES PILOTA_ISCRITTO (IdEdizione, IdPilota)
);

CREATE TABLE PRESTAZIONE_WEEKEND (
    IdGranPremio INT UNSIGNED NOT NULL,
    IdEdizione INT UNSIGNED NOT NULL,
    IdPilota INT UNSIGNED NOT NULL,
    PosizionamentoQualifica INT UNSIGNED,
    PosizionamentoGara INT UNSIGNED,
    Penalizzato BOOLEAN,
    RegistraGiroVeloce BOOLEAN,
    PunteggioFantasy INT,
    CONSTRAINT PK_PRESTAZIONE_WEEKEND
        PRIMARY KEY (IdEdizione, IdPilota, IdGranPremio),
    CONSTRAINT CK_PRESTAZIONE_POS_QUALIFICA
        CHECK (PosizionamentoQualifica IS NULL
            OR PosizionamentoQualifica BETWEEN 1 AND 20),
    CONSTRAINT CK_PRESTAZIONE_POS_GARA
        CHECK (PosizionamentoGara IS NULL
            OR PosizionamentoGara BETWEEN 1 AND 20),
    CONSTRAINT FK_PRESTAZIONE_PILOTA
        FOREIGN KEY (IdEdizione, IdPilota)
        REFERENCES PILOTA_ISCRITTO (IdEdizione, IdPilota),
    CONSTRAINT FK_PRESTAZIONE_WEEKEND
        FOREIGN KEY (IdEdizione, IdGranPremio)
        REFERENCES WEEKEND_DI_GARA (IdEdizione, IdGranPremio)
);

CREATE TABLE PARTECIPAZIONE_TEAM (
    IdLega INT UNSIGNED NOT NULL,
    IdTeam INT UNSIGNED NOT NULL,
    CONSTRAINT PK_PARTECIPAZIONE_TEAM
        PRIMARY KEY (IdLega, IdTeam),
    CONSTRAINT FK_PARTECIPAZIONE_TEAM_LEGA
        FOREIGN KEY (IdLega)
        REFERENCES LEGA (IdLega),
    CONSTRAINT FK_PARTECIPAZIONE_TEAM_TEAM
        FOREIGN KEY (IdTeam)
        REFERENCES TEAM_FANTASY (IdTeam)
);

CREATE TABLE RISULTATO_TEAM (
    IdEdizione INT UNSIGNED NOT NULL,
    IdGranPremio INT UNSIGNED NOT NULL,
    IdTeam INT UNSIGNED NOT NULL,
    PunteggioWeekend INT NOT NULL,
    CONSTRAINT PK_RISULTATO_TEAM
        PRIMARY KEY (IdEdizione, IdGranPremio, IdTeam),
    CONSTRAINT FK_RISULTATO_TEAM_TEAM
        FOREIGN KEY (IdTeam, IdEdizione)
        REFERENCES TEAM_FANTASY (IdTeam, IdEdizione),
    CONSTRAINT FK_RISULTATO_TEAM_WEEKEND
        FOREIGN KEY (IdEdizione, IdGranPremio)
        REFERENCES WEEKEND_DI_GARA (IdEdizione, IdGranPremio)
);
